---
on:
  workflow_dispatch:

jobs:
  BuildResume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # TODO: Containerized Build
      - uses: actions/upload-artifact@v2
        with:
          name: resume
          path: resume.pdf
